### ISSUE TITLE
报错，docker运行

### ISSUE THREAD

**Issue by shenfu1991** [cookeem/chatgpt-stream#2]
网页显示
<pre>
[CONNECT ERROR]
[CONNECT CLOSED]
</pre>

查看docker日志，

<pre>
33#33: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, req
</pre>

**Comment by shenfu1991** [comment]
用build方式也报错了：
<pre>
FO  Starting development server...
10% building 2/5 modules 3 active ...ream/node_modules/eslint-loader/index.js??ref--14-0!/root/chatgpt-stream/src/main.jsError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/root/chatgpt-stream/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/root/chatgpt-stream/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/root/chatgpt-stream/node_modules/webpack/lib/NormalModule.js:471:10)
    at /root/chatgpt-stream/node_modules/webpack/lib/NormalModule.js:503:5
    at /root/chatgpt-stream/node_modules/webpack/lib/NormalModule.js:358:12
    at /root/chatgpt-stream/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/root/chatgpt-stream/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/root/chatgpt-stream/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /root/chatgpt-stream/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/root/chatgpt-stream/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/root/chatgpt-stream/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/root/chatgpt-stream/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/root/chatgpt-stream/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /root/chatgpt-stream/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/root/chatgpt-stream/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/root/chatgpt-stream/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/root/chatgpt-stream/node_modules/webpack/lib/NormalModule.js:471:10)
    at /root/chatgpt-stream/node_modules/webpack/lib/NormalModule.js:503:5
    at /root/chatgpt-stream/node_modules/webpack/lib/NormalModule.js:358:12
    at /root/chatgpt-stream/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/root/chatgpt-stream/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/root/chatgpt-stream/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/root/chatgpt-stream/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /root/chatgpt-stream/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /root/chatgpt-stream/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.14.2
</pre>

**Comment by cookeem** [comment]
对于高版本的npm，出现`ERR_OSSL_EVP_UNSUPPORTED `这个错误请调整构建命令为：

```bash
export NODE_OPTIONS=--openssl-legacy-provider && npm run build
```

**Comment by cookeem** [comment]
运行chatgpt-stream需要先运行后端服务chatgpt-service

**Comment by shenfu1991** [comment]
@cookeem 感谢，mac下成功运行，不过好像这个不是连续对话，还有就是发送成功后最好把输入框内容清空了。🙏

**Comment by cookeem** [comment]
现在支持上下文对话了
